name: elsirat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.8
  dio: ^5.8.0+1
  firebase_auth: ^5.5.4
  firebase_core: ^3.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.2.1
  flutter_localizations:
    sdk: flutter
  flutter_qiblah: ^3.1.0+1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  geolocator: ^13.0.4
  google_nav_bar: ^5.0.7
  google_sign_in: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  location: ^8.0.0
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  timezone: ^0.10.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/data/azkar_sabah.json
    - assets/data/husn_en.json
    - assets/data/quran.json
    - assets/images/
    - assets/icons/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
